### ISSUE TITLE
Pagination Support for SQL Services

### ISSUE THREAD

**Issue by pumbas600** [GuusLieben/Hartshorn#457]
**Is your feature request related to a problem? Please describe.**
Consider a situation where you're creating a leaderboard. You don't want to display all the results in the database as there are too many, so you need to be able to display results using some form of pagination. This means you should be able to retrieve results from the database based on:
1. The number of items in a page.
2. The page number you're currently retrieving items for.

**Describe the solution you'd like**
Some way to easily retrieve a 'page' of results from a database, with the option to sort a specific column in ascending / descending order.

Ideally, this information should be contained within an object that can be passed to a service, as it would be convenient, that if this was specified as a parameter for a method annotated with `@Query` (#451) it would automatically be configured to handle the pagination.

**Additional context**
Spring currently has a `Pageable` object, as described by Baeldung [here](https://www.baeldung.com/spring-data-jpa-pagination-sorting).

**Comment by GuusLieben** [comment]
Depends on #467, I opened a draft PR for it at #474
