### ISSUE TITLE
`@Value` fields never fall back to inline value

### ISSUE THREAD

**Issue by GuusLieben** [GuusLieben/Hartshorn#605]
If a field annotated with `@Value` is defined as seen below, without the `sample.key` property being set, the value will always fall back to an empty or default value (in this case an empty `String`).
```java
@Value("sample.key")
private String key = "myDefaultValue";
```
Expected behavior would be to fall back to `"myDefaultValue"`, as it is set inline, and should only be changed if the property is set or an alternative value is defined in the `@Value` annotation.

**Comment by pumbas600** [comment]
Might even not need the `or` parameter in `@Value` as I feel like this makes more sense, especially for non-string types?

**Comment by GuusLieben** [comment]
Agreed, that would also simplify the value population and type checking
