### ISSUE TITLE
Add processing toggle permission to component stereotypes

### ISSUE THREAD

**Issue by GuusLieben** [GuusLieben/Hartshorn#639]
### Related problem

Currently all components are automatically processed when it passes any `ComponentProcessor`'s preconditions. However, it may not always be desired that a component is processed. This may be to circumvent specific modifications, for testing purposes, or other specific use-cases. 

### Requested feature

Add a toggle permission to the component stereotype: `#processComponent` which defaults to `true`. If the component indicates it does not wish to be processed, the processing queue should skip the component.

**Comment by pumbas600** [comment]
Perhaps this could be achieved by adding a `@DisableComponent` annotation to the component?

**Comment by GuusLieben** [comment]
> Perhaps this could be achieved by adding a `@DisableComponent` annotation to the component?

That would likely lead to ambiguity as the component will still be registered to the active component locator, while the name `DisableComponent` suggests the component is globally disabled.  

Likewise, `#permitProxying` is also a stereotype attribute, so adding a separate annotation for component processing would be inconsistent
