### ISSUE TITLE
Fallback sources for `@Configuration`

### ISSUE THREAD

**Issue by pumbas600** [GuusLieben/Hartshorn#656]
### Related problem

Considering the context of Halpbot, I have a configuration file that's used to specify certain aspects of your bot. A simplified version of this is shown below:
```java
@Getter
@Configuration(source = "classpath:bot-config", filetype = FileFormats.PROPERTIES)
public class BotConfiguration
{
    @Value("defaultPrefix")
    private String defaultPrefix = "";

    @Value("ownerId")
    private long ownerId = -1;
}
```
Currently, this configuration file must be specified in the `resources` folder, which may be what some people want to do for their bot, but I would also like it to be possible to find it in the root folder if it's present in the resource folder (As some people may not want it to be built into their jar file, allowing them to easily adjust the values without rebuilding their bot). Currently, this is not possible.

### Requested feature

I suggest that the `source` field be changed to an array of strings, where it iterates through the array in order until it finds the file. This allows you to specify multiple allowed places for the file to be located.

For example:

```java
@Getter
@Configuration(source = { "classpath:bot-config", "bot-config" }, filetype = FileFormats.PROPERTIES)
public class BotConfiguration
{
    @Value("defaultPrefix")
    private String defaultPrefix = "";

    @Value("ownerId")
    private long ownerId = -1;
}
```

Would first check the classpath for `bot-config.properties` and if that isn't present, it would then the root directory for it (I'm not sure if there's meant to be a specific prefix for this, like there is with classpath)

**Comment by GuusLieben** [comment]
> I'm not sure if there's meant to be a specific prefix for this, like there is with classpath
If no strategy is defined it'll default to a FS-based lookup. I'll document this in `@Configuration`

> Considering the context of Halpbot [..]
For future readers: https://github.com/pumbas600/HalpBot/

**Comment by GuusLieben** [comment]
I like the proposed solution, it's simple yet effective, and will integrate nicely with #650
