### ISSUE TITLE
Proxy equality does not work with self

### ISSUE THREAD

**Issue by pumbas600** [GuusLieben/Hartshorn#665]
### Version

22.1

### Problem/Opportunity

A proxy does not equal itself when using `this` and itself as another object. This is best illustrated in the test below:

**The service:**

```java
@Service
public class TestService
{
    @Inject
    private ApplicationContext applicationContext;

    public boolean test(TestService self) {
        return this.equals(self); // returns false
    }
}
```

**The unit test:**

```java
@InjectTest
public void proxyThisEquality(TestService testService) {
    Assertions.assertEquals(testService, testService); // true
    Assertions.assertTrue(testService.test(testService)); // false
}
```

**Why is this important?** 

In Halpbot (https://github.com/pumbas600/Halpbot),  some individuals may register their bot class as an event listener with JDA (Either from habit or from not reading the documentation), however, Halpbot automatically registers any event listeners annotated with `@Service`. To prevent event listeners from being registered twice, Halpbot removes any double-up event listeners (JDA doesn't offer the ability to check if the list of event listeners contains an object, only the ability to remove them).

However, as `this` doesn't equal itself, the double-ups are not removed.

**Comment by GuusLieben** [comment]
Will see what is possible in #703, the use of `this` is a black box inside proxies, as it may refer to either the proxy instance or original delegate, depending on whether the `test` method is proxied or not.

**Comment by GuusLieben** [comment]
To explain why this happens; when you define a concrete method in a concrete type, any method calls to this method will be delegated to a non-proxied instance of the type. This means that the provided instance (which is a proxy) is indeed not equal to the current instance (as it is not a proxy). To provide a sample:
```java
public class EqualProxy {
    public boolean test(final EqualProxy self) {
        return this.equals(self);
    }
}
```
yields:
![image](https://user-images.githubusercontent.com/10957963/153767227-4acbae33-333e-4d0a-bee9-e4641b1da728.png)

In the case of interface- and abstract proxies, this behavior is different as there is no capable concrete instance. In this case, the equals call is handled by the proxy's method handlers. Specifically, this bit handles it (also used in #704):
https://github.com/GuusLieben/Hartshorn/blob/c32018d49327056ce9a1bdd350b903a2538a1624/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/javassist/JavassistProxyHandler.java#L191-L195

In this case, but the object and proxy object are the same, so they are also equal as suggested by the last line of that equality rule:
https://github.com/GuusLieben/Hartshorn/blob/c32018d49327056ce9a1bdd350b903a2538a1624/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/javassist/JavassistProxyHandler.java#L194

So, to provide a reliable solution; a while back I introduced the `@Unproxy` annotation for processing potential proxy parameters. The advantage here is that this annotation allows you to get the delegate instance of a proxy, if it exists. Depending on the usecase, you can configure it to fallback to the proxy instance, or `null` if no such delegate exists.  
https://github.com/GuusLieben/Hartshorn/blob/c32018d49327056ce9a1bdd350b903a2538a1624/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/annotations/Unproxy.java#L24-L36

This may yield the concern that the parameters may not be processed, as the method is concrete. However, all methods of a proxy are always processed, even if they are not explicitely intercepted.
https://github.com/GuusLieben/Hartshorn/blob/c32018d49327056ce9a1bdd350b903a2538a1624/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/javassist/JavassistProxyHandler.java#L127
https://github.com/GuusLieben/Hartshorn/blob/c32018d49327056ce9a1bdd350b903a2538a1624/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/javassist/JavassistProxyHandler.java#L133-L135

To resolve your situation, you could thus use the following:
```java
public boolean test(final @Unproxy EqualProxy self) {
    return this.equals(self);
}
```
Which, as expected, yields the delegate instance, and returns `true`
![image](https://user-images.githubusercontent.com/10957963/153767561-9ee57d0d-48cd-4592-9d37-15717a5fc7cf.png)

These capabilities remain stable even after HEP703 (#704), but are already correctly operating in the latest releases.

**Comment by GuusLieben** [comment]
See 005efc3ee73bb0756c3d235fd25159ed3052a744 for additional test-cases for this scenario

**Comment by GuusLieben** [comment]
Found a potential additional solution for concrete method calls, will validate and report back here later today.

**Comment by GuusLieben** [comment]
To recap; I added an additional rule to only use the pre-existing service delegate for abstract methods. This allows processors to add a concrete implementation for abstract service types where needed, while not directly intercepting concrete methods which can be executed directly using the proxy instance.  

As a result, the need for `@Unproxy` is (in this scenario) no longer relevant. The following is now a valid solution:
```java
@Service
// Abstract to trigger basic delegate proxying, and ensure no delegate can exist
public abstract class EqualServiceProxy {
    public boolean test(final EqualServiceProxy self) {
        return this.equals(self);
    }
}
```
```java
@Test
void testServiceSelfEquality() {
    final EqualServiceProxy service = this.applicationContext.get(EqualServiceProxy.class);
    Assertions.assertEquals(service, service);
    Assertions.assertTrue(service.test(service));
}
```
Yields (in `#test`):
![image](https://user-images.githubusercontent.com/10957963/153769209-d677680a-c199-4266-86e5-f46c25ee9217.png)
