### ISSUE TITLE
Deprecate Tasks (`hartshorn-tasks`) API

### ISSUE THREAD

**Issue by GuusLieben** [GuusLieben/Hartshorn#667]
### Related problem

The Tasks API has gone largely unused, the only reference to `ThreadUtils` being an unused reference in the `SimpleCommandCLI` (to be removed), and the `TaskRunner` being used once in the `CacheImpl` (to be replaced).

https://github.com/GuusLieben/Hartshorn/blob/21a262a874a430ff190f9152a40a5f3fd22f2a95/hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/cli/SimpleCommandCLI.java#L46

https://github.com/GuusLieben/Hartshorn/blob/21a262a874a430ff190f9152a40a5f3fd22f2a95/hartshorn-cache/src/main/java/org/dockbox/hartshorn/cache/CacheImpl.java#L72

### Requested feature

The following types should be marked for removal (in alphabetical order):
- `AbstractTask`
- `PipelineTask`
- `SimpleTaskRunner`
- `Task`
- `TaskRunner`
- `ThreadUtils`
- `ThreadUtilsImpl`

This leaves only the Pipeline API. As this is currently unused in Hartshorn, I suggest deprecating it for removal, but move it to a separate repository **before** deprecation.  

As I am not the sole contributor to this API, I request permission from @pumbas600 for this to be moved before deprecation. As he originally wrote the API, I'll leave it up to him whether he prefers it to be on a repository created by himself, or by me.

**Comment by pumbas600** [comment]
I don't mind, you can create a repository for it if you want. In complete honesty, I was never completely satisfied with the implementation of the pipeline API. It always felt a little constricted.

**Comment by GuusLieben** [comment]
Will refactor usages and mark the existing API for deprecation later today. I have moved the Pipeline API to https://github.com/GuusLieben/JPipelines
