### ISSUE TITLE
Switch license to Apache 2.0

### ISSUE THREAD

**Issue by GuusLieben** [GuusLieben/Hartshorn#668]
We originally opted for the GNU Lesser General Public License (v2.1), or LGPLv2.1, to restrict the publication of implementation-specific usages. However, we are now almost 1.5 years further, and have since shifted the primary focus of the Hartshorn framework drastically. Even more so, the project doesn't even carry the same name anymore.  

To lift the restrictions introduced by LGPLv2.1, I hereby propose we change the license for the Hartshorn framework in its current and future state to the Apache 2.0 license. This affects all sub-projects of the Hartshorn framework, which are listed below.
- Hartshorn Core CDI: https://github.com/GuusLieben/Hartshorn/tree/develop/hartshorn-core
- Hartshorn Cache: https://github.com/GuusLieben/Hartshorn/tree/develop/hartshorn-cache
- Hartshorn Commands: https://github.com/GuusLieben/Hartshorn/tree/develop/hartshorn-commands
- Hartshorn Config: https://github.com/GuusLieben/Hartshorn/tree/develop/hartshorn-config
- Hartshorn Data: https://github.com/GuusLieben/Hartshorn/tree/develop/hartshorn-data
- Hartshorn Events: https://github.com/GuusLieben/Hartshorn/tree/develop/hartshorn-events
- Hartshorn Internationalization (I18n): https://github.com/GuusLieben/Hartshorn/tree/develop/hartshorn-i18n
- Hartshorn Tasks: https://github.com/GuusLieben/Hartshorn/tree/develop/hartshorn-tasks
- Hartshorn Test Suite: https://github.com/GuusLieben/Hartshorn/tree/develop/hartshorn-test-suite
- Hartshorn Web: https://github.com/GuusLieben/Hartshorn/tree/develop/hartshorn-web

For all projects the change will take effect immediately after all contributors have agreed. Release 22.1 and earlier releases will remain available under the LGPLv2.1 license.

**Comment by GuusLieben** [comment]
@pumbas600 and @simbolduc, if you agree with the above, please respond to this issue in the form of a comment (reactions to other comments are difficult to track in the public record).

**Comment by pumbas600** [comment]
I also accept these changes
